spring.application.name=IncidentReplay

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/incidentreplay

# Server Port
server.port=8080

# Replay Target Configuration
incidentreplay.replay.target-base-url=http://localhost:8081

incidentreplay.replay.timeout-ms=5000
